spring:
   application:
     name: ums
     
security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
billingEndpoint: https://billing-nice-topi.apps.cumuluslabs.io/
